# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 00:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_1', models.CharField(max_length=128, null=True)),
                ('line_2', models.CharField(max_length=128, null=True)),
                ('city', models.CharField(max_length=128, null=True)),
                ('state', models.CharField(max_length=128, null=True)),
                ('lat', models.FloatField(default=-185.0)),
                ('lng', models.FloatField(default=-185.0)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalShop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('phone', models.CharField(blank=True, max_length=13, null=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medicine.Address')),
            ],
        ),
    ]
