# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-14 08:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medtypeid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medtype_id', models.IntegerField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('med_name', models.CharField(max_length=1000)),
                ('med_dosage', models.FloatField(blank=True, null=True)),
                ('med_quantity', models.IntegerField()),
                ('med_price', models.FloatField()),
                ('medtype_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medicine.Medtypeid')),
            ],
        ),
    ]
