# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-14 17:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0005_remove_medtypeid_medtype_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='medtypeid',
            name='medtype_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='products',
            name='medtype_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='medicine.Medtypeid'),
        ),
    ]
