# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-14 17:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0006_auto_20170414_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='medtype_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='medicine.Medtypeid'),
        ),
    ]
