# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-14 17:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0007_auto_20170414_1718'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Medtypeid',
            new_name='Medtypeid1',
        ),
    ]
