# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-14 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0008_auto_20170414_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='medtypeid1',
            name='med_type',
            field=models.CharField(default='Not_Valid', max_length=200),
        ),
    ]
