# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-14 17:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0010_auto_20170414_1748'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medtype_id', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='products',
            name='medtype_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicine.Type'),
        ),
        migrations.DeleteModel(
            name='Medtypeid1',
        ),
    ]
