# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-14 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0011_auto_20170414_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='med_type',
            field=models.CharField(default='null', max_length=200),
        ),
    ]
