# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-14 23:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0012_type_med_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='type',
            name='med_type',
        ),
    ]
