# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-14 23:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0013_remove_type_med_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='medtype_id',
            field=models.IntegerField(verbose_name=3),
        ),
    ]
