# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-14 23:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0014_auto_20170414_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='medtype_id',
            field=models.IntegerField(),
        ),
    ]
